### ISSUE TITLE
Setting initial frequency for signal

### ISSUE THREAD

**Issue by mcguirepr89** [daviddavini/pysinewave#11]
Hello and thank you very much for putting this together!

I am very interested in using the `SineWave.set_frequency(hertz)` and `SineWave.set_amplitude(percent)` functions for a software approach to (specifically this) [heterodyne frequency shifting](https://marcelmg.github.io/bat_detector/) technique.

Thus, I'm hoping to generate some sine signals with specific frequencies, though I'm unsure exactly how to get the SineWave to _initialize_ with the frequency that I'm setting in my `SineWave.set_frequency(hertz)` function.

The code I'm tinkering with is below. The goal for now is simply to generate a SineWave with the specified frequency.

I apologize in advance for any difficulty there might be in getting me to understand such an esoteric concept and for sucking at python! (There is a real chance than I'm just shitty at Python and have some syntax issues when trying to use the function.)

Take 1:
```
import time
from pysinewave import SineWave

# Create a sine wave
sinewave = SineWave()

# Set the frequency
sinewave.set_frequency(9000)

# Play the sound
sinewave.play()
time.sleep(2)
sinewave.stop()
exit()
```
The script above eventually reaches the 9000Hz I'm aiming for, but begins with a much lower default SiveWave from which the frequency shifts up to my specified frequency.

Take 2:
```
import time
from pysinewave import SineWave

# Create a sine wave
sinewave = SineWave.set_frequency(9000)

# Play the sound
sinewave.play()
time.sleep(2)
sinewave.stop()
exit()
```
The second attempt (in the script above) fails with this traceback:
```
Traceback (most recent call last):
  File "/home/patrick/./sinewave.py", line 5, in <module>
    sinewave = SineWave.set_frequency(9000)
TypeError: set_frequency() missing 1 required positional argument: 'frequency'
```

Again, I'm really sorry if you've made this really easy for folks who are a bit more python-savvy than I to discern for themselves how to do this, and I certainly don't want my inquiry to imply any deficit in the documentation -- on the contrary, I appreciate the time taken to funnel most users towards using `pitch` over `frequency`. For any other use case, I would certainly stay within the recommended setup, though I think the only way to generate these ultrasonic frequencies is to be explicit using a Hertz unit.

My very best regards and another _thanks_ for this great toolset~~
Patrick

**Comment by mcguirepr89** [comment]
Sorry!!!  I used this to figure it out!!! Thanks again!!!!

**Comment by iddq** [comment]
How is it possible to play a single tone without frequency transition?
