### ISSUE TITLE
Pitch/Frequency Conversion

### ISSUE THREAD

**Issue by ebarnz** [daviddavini/pysinewave#7]
If this isn't the right place for this I apologize, but in the readme under "A Note on Pitch on Volume" it gives the conversion from pitch to frequency as **frequency = 440 * 2^((pitch-9)/2)**. I think this is a typo, as it should probably be **frequency = 440 * 2^((pitch-9)/12)**. This isn't the most important since it's correct in the code, but it did confuse me for a little.

Otherwise thank you for this, it's a helpful tool.

**Comment by WanderingApps** [comment]
@ebarnz - Would you be so kind to help me with the reverse.  If I have the frequency in Hz, how can I get the pitch value?  Logarithms are no longer my wheelhouse!

**Comment by ebarnz** [comment]
@WanderingApps That is correct.

**Comment by daviddavini** [comment]
Good catch, thanks for the help! I definitely meant to divide by 12.

Fixed in a6f346003a87758a55516391b1415b005e5e7279.
