### ISSUE TITLE
Push new release to PyPi

### ISSUE THREAD

**Issue by obfuscatedgenerated** [daviddavini/pysinewave#8]
The PyPi version does not contain the features in this repo such as channels.

**Comment by obfuscatedgenerated** [comment]
In addition, because the build folder has been committed, you cannot simply specify the repo url into the install command instead as it favours the build folder, which doesn't have the features.

**Comment by obfuscatedgenerated** [comment]
Actually, I think the reason the repo url wasn't working was because the version was already cached, but pushing the build/dist directories is still a bad practice.

**Comment by daviddavini** [comment]
PyPi has the latest release now, also I just removed build/dist in 42e7b7a7e16985c733b08943e64cb4709f36c7f5. Thanks!
